# Default values for freeton-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: skyson/freeton-validator
  tag: cpp
  pullPolicy: Always

env:
  MY_ADDR: 
  STAKE: 13000
  FIFTPATH: /opt/net.ton.dev/crypto/fift/lib/:/opt/net.ton.dev/ton/crypto/smartcont/

nameOverride: ""
fullnameOverride: ""

fluentd-cloudwatch:
  enabled: true
  awsRegion: us-west-2
  awsAccessKeyId: 
  awsSecretAccessKey: 
  rbac:
    create: true

containerPort:
  adnl: 30310
#  lite: 32767

service:
  type: NodePort

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: node.ton
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
# Test requests/limits
#  limits:
#    cpu: 100m
#    memory: 5Mi
#  requests:
#    cpu: 100m
#    memory: 512Mi
# Minimum requests/limits
  limits:
    cpu: 4000m
    memory: 16Gi
  requests:
    cpu: 2000m
    memory: 8Gi
# Recommended requests/limits
#  limits:
#    cpu: 8000m
#    memory: 32Gi
#  requests:
#    cpu: 8000m
#    memory: 32Gi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 1000Gi
