apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeton-node.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app.kubernetes.io/name: {{ include "freeton-node.name" . }}
    helm.sh/chart: {{ include "freeton-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containerPort.adnl }}
      targetPort: {{ .Values.containerPort.adnl }}
      nodePort: {{ .Values.containerPort.adnl }}
      protocol: UDP
      name: freeton-adnl
  selector:
    app.kubernetes.io/name: {{ include "freeton-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
